version: '2'

services:
  web:
    container_name : redis-web
    build: .
    ports:
      - 9080:80
    volumes:
      - ./src/html:/var/www/html/
    links:
      - mysql:mysql
      - redis:redis
  mysql: 
    container_name : redis-mysql
    image: mysql:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 212224
      MYSQL_ROOT_PASSWORD: 212224
    ports: 
      - "33066:3306"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/mysql:/var/lib/mysql
    
      